# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: a464a6bc8a505cbc99b330f815dffd9aab79c066736c08bf514321cfb8e9c97a3bd6d787ee1ff797f10d8ea74d53103565304a8565acfdf7789da4991871bcd1

test:
  secret_key_base: 83b9b640467e6cfa0db4802fe1e3ff256bd39df386278e1725f0f490d8d3ac5a9ed42636eb41b0ea66b0fd01e6d24be1f695faae4e331ad4e7eee9054cb140b8

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
